--1번
SELECT EMP_NAME,TRUNC(SYSDATE - HIRE_DATE) "근무일수1",
				TRUNC(SYSDATE - HIRE_DATE) "근무일수2"
FROM EMPLOYEE;

--2번

SELECT EMP_ID,EMP_NAME,EMAIL,PHONE 
FROM EMPLOYEE
WHERE MOD(EMP_ID,2) = 1;

--WHERE SUBSTR(EMP_ID,-1,1) IN(1,3,5,7,9); 

--3번
SELECT *
FROM EMPLOYEE
WHERE (MONTHS_BETWEEN(SYSDATE, HIRE_DATE )/12) >=20;
--WHERE EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE) >=20;

--4번

SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO,1,8) ,13, '*') "주민등록번호",
	   REPLACE(EMP_NO, SUBSTR(EMP_NO,9), '******') "주민등록번호",
       SUBSTR(EMP_NO,1,8)||'******' "주민등록번호" 
FROM EMPLOYEE ;



--5번
SELECT EMP_NAME,JOB_CODE,TO_CHAR(NVL((SALARY+(SALARY*BONUS))*12,SALARY*12)
						,'L999,999,999')"연봉(원)",
	  TO_CHAR((SALARY+(SALARY*NVL(BONUS,0))*12)
						,'L999,999,999')"연봉(원)"
FROM EMPLOYEE;

--6번
SELECT EMP_ID,EMP_NAME,DEPT_CODE ,HIRE_DATE 
FROM EMPLOYEE
WHERE  (DEPT_CODE = 'D9' OR DEPT_CODE = 'D5')
--WHERE DEPT_CODE IN ('D5','D9)
--AND EXTRACT(YEAR FROM HIRE_DATE) = '2004'
AND TO_CHAR(HIRE_DATE, 'YYYY') = '2004';

--7번
SELECT EMP_NAME,HIRE_DATE
	   ,EXTRACT (DAY FROM (LAST_DAY(HIRE_DATE)
       -EXTRACT (DAY FROM HIRE_DATE)+1)) "입사한 달의 근무"
       ,LAST_DAY(HIRE_DATE)-HIRE_DATE+1 "입사한 달의 근무"
FROM EMPLOYEE;

-- 


--8번

SELECT EMP_NAME, DEPT_CODE,EMP_NO, TO_CHAR(TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD')
    					  	,'YY"년" MM"월" DD"일"') "생년월일",
 --잘못된 방법                	FLOOR((SYSDATE-TO_DATE((SUBSTR(EMP_NO,1,6))))/365)"만 나이",
       TO_CHAR(TO_DATE(SUBSTR(EMP_NO,1,6)),'YY"년" MM"월" DD"일"') "생년월일",
       FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE((SUBSTR(EMP_NO,1,6))))/12) "만 나이",
       ((SYSDATE-TO_DATE((SUBSTR(EMP_NO,1,6))))/365)"만 나이" --오차발생
FROM EMPLOYEE;




