--1번
SELECT EMP_NAME,TRUNC(SYSDATE - HIRE_DATE) "근무일수1",
				TRUNC(SYSDATE - HIRE_DATE) "근무일수2"
FROM EMPLOYEE;

--2번

SELECT EMP_ID,EMP_NAME,EMAIL,PHONE 
FROM EMPLOYEE
WHERE MOD(EMP_ID,2) = 1;

--3번
SELECT *
FROM EMPLOYEE
WHERE (MONTHS_BETWEEN(SYSDATE, HIRE_DATE )/12) >=20;

--4번

SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO,1,8) ,13, '*') "주민등록번호"
FROM EMPLOYEE ;

--5번
SELECT EMP_NAME,JOB_CODE,TO_CHAR(NVL((SALARY+(SALARY*BONUS))*12,SALARY*12)
						,'L999,999,999')"연봉(원)"
FROM EMPLOYEE;

--6번
SELECT EMP_ID,EMP_NAME,DEPT_CODE ,HIRE_DATE 
FROM EMPLOYEE
WHERE  (DEPT_CODE = 'D9' OR DEPT_CODE = 'D5')
AND EXTRACT(YEAR FROM HIRE_DATE) = '2004';

--7번
SELECT EMP_NAME,HIRE_DATE,EXTRACT (DAY FROM (LAST_DAY(HIRE_DATE)
                          -EXTRACT (DAY FROM HIRE_DATE)+1)) "입사한 달의 근무"
FROM EMPLOYEE;

-- 


--8번

SELECT EMP_NAME, DEPT_CODE, TO_CHAR(TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD'),'YY"년" MM"월" DD"일"') "생년월일",
                          	FLOOR((SYSDATE-TO_DATE((SUBSTR(EMP_NO,1,6))))/365)"만 나이"
FROM EMPLOYEE;
