--학과명 계열
SELECT DEPARTMENT_NAME 학과명,CATEGORY 계열
FROM TB_DEPARTMENT;

--2학과의 학과 정원 다음과 같음

SELECT DEPARTMENT_NAME||'의 정원은 ' 학과별,CAPACITY ||'명 입니다' 정원
FROM TB_DEPARTMENT;

--3."국어국문학과"에 다니는 여학생중 현재 휴악중인 여학생 찾아달라요청 누?

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001'
AND SUBSTR(STUDENT_SSN,8,1) = '2'
AND ABSENCE_YN = 'Y';

--4.도서관 장기 대출 연체자들 찾아  이름 계시
--A513079,A513090,A513091,A513110,A513119

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO = ANY('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;

--5.입학정원이 20이상 30명 이하인 학과들의 학과 이름과 계열을 출력
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6.춘 기술대학교는 총장을 제외하고 모든 교수들이 소속 학과를 가지고 있다. 총장의 이름을 알아내라

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO IS NULL;

--7.혹시 전산상의 착오로 학과가 지정되어 있지 않느 학생이 있는지 확인한다

SELECT DEPARTMENT_NO,STUDENT_NAME 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO IS NULL;

--8.수강신청을 하려고한다. 선수과목 여부를 확인해야되는데, 선수과목이 존재하는 과목들은 어떤 과목인지 과목번호를 조회

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9.춘 대학에는 어떤 계열(CATEGORY)들이 있는지 조회해보시오.

SELECT DISTINCT  CATEGORY
FROM TB_DEPARTMENT;

--10. 02학번 전주 거주자들의 모임을 만들려고 한다. 휴학한 사람들은 제외한 재학중인 학생들의 
--    학번, 이름, 주민번호를 출력하는 구문

SELECT STUDENT_NO,STUDENT_NAME, STUDENT_SSN,ENTRANCE_DATE
FROM TB_STUDENT 
WHERE ABSENCE_YN IN 'N'
AND STUDENT_ADDRESS LIKE '%전주%'
AND EXTRACT (YEAR FROM ENTRANCE_DATE) = 2002; 


